name: chat_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.4.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cloud_firestore: ^5.4.5
  uuid: ^4.5.1
  intl: ^0.19.0
  awesome_notifications: ^0.10.0
  firebase_messaging: ^15.1.5
  dio: ^5.7.0
  envied: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  envied_generator: ^1.0.0

flutter:
  uses-material-design: true
